// DS-1 standard: use Phosphor as the single runtime icon library.
// Phosphor already has the majority footprint across product code, so this file
// is the compatibility boundary for legacy Lucide-style icon names.
//
// Icon size conventions:
// - `h-4 w-4` / `size={16}` for dense inline UI and helper text.
// - `h-5 w-5` / `size={20}` for default actions, lists, and form affordances.
// - `h-6 w-6` / `size={24}` for headers, empty states, and emphasized actions.

export * from '@phosphor-icons/react';

export {
  Airplane as Plane,
  AppleLogo as Apple,
  ArrowCircleUp as ArrowUpCircle,
  ArrowClockwise as RefreshCw,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowElbowDownRight as CornerDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut as ExternalLink,
  ArrowUpRight,
  ArrowsDownUp as ArrowUpDown,
  ArrowsClockwise,
  ArrowsCounterClockwise as RefreshCcw,
  ArrowsLeftRight as ArrowRightLeft,
  Backspace as Delete,
  Bank as Landmark,
  Barbell as Dumbbell,
  Bell,
  Bell as BellPlus,
  BellRinging as BellRing,
  Brain as Bot,
  Calendar,
  CalendarDots as CalendarClock,
  CalendarDots as CalendarDays,
  CalendarX as CalendarX2,
  Camera,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  ChartBar as BarChart,
  ChartBar as BarChart3,
  ChartLine as ChartArea,
  ChartPieSlice as PieChart,
  Check,
  CheckCircle,
  CheckCircle as CheckCircle2,
  Circle,
  CircleNotch as Loader2,
  CircleNotch as LoaderCircle,
  Clock,
  Clock as Clock3,
  Coins,
  Coffee,
  CurrencyDollar as DollarSign,
  Circuitry as BrainCircuit,
  DeviceMobile as Smartphone,
  DotsThreeVertical as EllipsisVertical,
  DotsThreeVertical as MoreVertical,
  Drop as Droplets,
  EnvelopeSimple as Mail,
  EnvelopeSimple as MailCheck,
  EyeSlash as EyeOff,
  FloppyDisk as Save,
  Flame,
  Funnel as Filter,
  ForkKnife as Utensils,
  GasPump as Fuel,
  GameController as Gamepad2,
  Gauge,
  HandCoins,
  Heartbeat as HeartPulse,
  House as Home,
  Info,
  Keyboard,
  Microphone as Mic,
  MusicNote as Music,
  Lightning as Zap,
  Lock,
  SignOut as LogOut,
  MagnifyingGlass as SearchX,
  Minus,
  MinusCircle,
  PaperPlaneTilt as Send,
  PiggyBank,
  Pizza,
  Plus,
  PlusCircle,
  Pulse as Activity,
  Receipt as ReceiptText,
  Scales as Scale,
  Shield,
  ShieldCheck,
  SpeakerHigh as Speaker,
  Sparkle as Sparkles,
  StarFour,
  Stack as Layers,
  Television as Tv,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Trophy,
  TShirt as Shirt,
  Warning as AlertTriangle,
  WarningCircle as AlertCircle,
  Wallet,
  Cards as WalletCards,
  WifiHigh as Wifi,
  WifiSlash as WifiOff,
  Wrench,
  X,
} from '@phosphor-icons/react';

